'use strict';
const {app,BrowserWindow,dialog,nativeImage}=require('electron');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
module.exports=async function({win,run,waitFor,checks,dir,profile}){
  assert.equal(app.getVersion(),'2.1.3');
  await run(`window.__qaErrors=[];window.addEventListener('error',e=>window.__qaErrors.push(e.message));window.addEventListener('unhandledrejection',e=>window.__qaErrors.push(String(e.reason?.message||e.reason)));`);
  async function capture(name){await new Promise(r=>setTimeout(r,200));fs.writeFileSync(path.join(dir,name+'.png'),(await win.webContents.capturePage()).toPNG());}
  for(const item of require('../src/assets/artwork-manifest.json'))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../src/assets/source',item.file))).digest('hex'),item.sha256);
  const nav=await run(`return [...document.querySelectorAll('#mainNav [data-view]')].map(e=>e.dataset.view);`);
  assert.equal(nav[0],'start');assert.equal(nav[1],'dashboard');
  await run(`setView('start');`);
  await waitFor(()=>run(`const img=document.querySelector('.start-art');return img.complete&&img.naturalWidth===1536;`),'Start artwork');
  assert.equal(await run(`return getComputedStyle(document.querySelector('.start-art')).objectFit;`),'contain');
  await capture('01-Start');checks.push('Start above Multi-Chat; original art SHA-256 and aspect ratio verified');
  await run(`setView('broadcast');document.querySelector('#bcNew').click();`);
  await waitFor(()=>run(`return !!document.querySelector('#bcForm');`),'Broadcast form');
  await run(`document.querySelector('#bcName').value='QA Broadcast A';document.querySelector('#bcInterval').value=30;document.querySelector('#bcDelay').value=0;document.querySelector('#bcEnabled').checked=true;document.querySelector('[data-bc-target=local]').checked=true;document.querySelector('[data-bc-target=cng]').checked=false;document.querySelector('[data-bc-message]').value='QA AUTO A';await document.querySelector('#bcForm').onsubmit({preventDefault(){}});`);
  await waitFor(()=>run(`return (await window.batto.getState()).config.autoBroadcast.items.length===1;`),'Save first broadcast');
  const first=(await run('return await window.batto.getState();')).config.autoBroadcast.items[0].id;
  await run(`await document.querySelector('#bcNew').onclick();document.querySelector('#bcName').value='QA Broadcast B';document.querySelector('#bcInterval').value=60;document.querySelector('#bcDelay').value=60;document.querySelector('[data-bc-message]').value='QA AUTO B';await document.querySelector('#bcForm').onsubmit({preventDefault(){}});`);
  assert.equal((await run('return await window.batto.getState();')).config.autoBroadcast.items.length,2);
  await run(`await document.querySelector('#bcDuplicate').onclick();`);
  assert.equal((await run('return await window.batto.getState();')).config.autoBroadcast.items.length,3);
  await run(`document.querySelector('#bcDelete').click();`);
  await waitFor(()=>run(`return !!document.querySelector('dialog[open]');`),'Delete confirmation');
  await run(`document.querySelector('dialog[open] button[value=yes]').click();`);
  await waitFor(()=>run(`return (await window.batto.getState()).config.autoBroadcast.items.length===2;`),'Delete duplicate persisted');
  await run(`document.querySelector('#bcMaster').checked=true;document.querySelector('#bcGlobalGap').value=0;document.querySelector('#bcPlatformGap').value=0;await document.querySelector('#bcMasterSave').onclick();`);
  await waitFor(()=>run(`return (await window.batto.getState()).messages.some(m=>m.message==='QA AUTO A');`),'Real scheduler local output');
  await run(`document.querySelector('[data-bc-select="${first}"]').click();`);
  await capture('03-Auto-Broadcast');
  await run(`document.querySelector('#bcDelete').click();`);
  await waitFor(()=>run(`return !!document.querySelector('dialog[open]');`),'Delete active schedule');
  await run(`document.querySelector('dialog[open] button[value=yes]').click();`);
  await waitFor(()=>run(`return !(await window.batto.broadcastStatus()).items.some(x=>x.id==='${first}');`),'Removed scheduler entry');
  await run(`document.querySelector('#bcMaster').checked=false;await document.querySelector('#bcMasterSave').onclick();`);
  checks.push('Real UI: create two schedules, duplicate, confirm delete, automatic local delivery, delete active schedule');
  await run(`setView('settings');`);
  await waitFor(()=>run(`return !!document.querySelector('#settingsTtsVolume');`),'Shared audio settings');
  await run(`document.querySelector('#settingsTtsVolume').value=37;await document.querySelector('#settingsTtsSave').onclick();`);
  assert.equal((await run('return await window.batto.getState();')).config.tts.volume,.37);
  await waitFor(()=>run(`return !!document.querySelector('#stChatImageUpload')&&!!document.querySelector('#chatBackgroundPreview');`),'Chat background settings');
  assert.equal((await run('return await window.batto.getState();')).config.appearance.chatBackground.mode,'preset');
  assert.match(await run(`return getComputedStyle(document.querySelector('#chatBackgroundPreview')).backgroundImage;`),/crazy-batto-chat-default/);
  const chatFixture=path.join(__dirname,'../src/assets/source/crazy-batto-chat-default.jpg');
  const originalOpenDialog=dialog.showOpenDialog;
  const uploadChatFixture=async()=>{
    dialog.showOpenDialog=async()=>({canceled:false,filePaths:[chatFixture]});
    try { await run(`await document.querySelector('#stChatImageUpload').onclick();`); }
    finally { dialog.showOpenDialog=originalOpenDialog; }
    return (await run('return await window.batto.getState();')).config.appearance.chatBackground.customPath;
  };
  const firstChatImage=await uploadChatFixture();
  assert.equal(fs.existsSync(firstChatImage),true);
  await run(`window.confirm=()=>true;await document.querySelector('#stChatImagePreset').onclick();`);
  await waitFor(()=>run(`return S.config.appearance.chatBackground.mode==='preset';`),'Restore bundled chat background');
  assert.equal(fs.existsSync(firstChatImage),false);
  const customChatImage=await uploadChatFixture();
  await waitFor(()=>run(`return S.config.appearance.chatBackground.mode==='custom';`),'Custom chat background persisted');
  assert.equal(fs.existsSync(customChatImage),true);
  assert.equal(await run(`return await new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image.naturalWidth===1080&&image.naturalHeight===1920);image.onerror=()=>resolve(false);image.src=S.assets.chatBackground.url;});`),true);
  await run(`document.querySelector('#stChatImageMain').checked=true;document.querySelector('#stChatImageFit').value='cover';document.querySelector('#stChatImagePosition').value='right center';document.querySelector('#stChatImageDarkness').value=63;await document.querySelector('#stChatImageSave').onclick();`);
  await waitFor(()=>run(`const b=S.config.appearance.chatBackground;return b.showInMain&&b.fit==='cover'&&b.position==='right center'&&b.darkness===.63;`),'Chat background controls persisted');
  assert.equal(await run(`return document.body.classList.contains('chat-background-active');`),true);
  assert.match(await run(`return getComputedStyle(document.querySelector('.chat-card')).backgroundImage;`),/chat-background-/);
  await run(`document.querySelector('#chatBackgroundSettings').scrollIntoView({block:'start'});`);await capture('04-Chatfenster-Bild');
  checks.push('Chat image: bundled Crazy_Batto preset, native upload, reset cleanup, preview, fit, position, darkness and main-window display');
  await waitFor(()=>run(`return !!document.querySelector('#stLocalIconUpload')&&!!document.querySelector('#localChatIconPreview');`),'Local chat icon settings');
  assert.equal((await run('return await window.batto.getState();')).config.appearance.chatIcons.local.mode,'default');
  const uploadLocalIconFixture=async()=>{
    dialog.showOpenDialog=async()=>({canceled:false,filePaths:[chatFixture]});
    try { await run(`await document.querySelector('#stLocalIconUpload').onclick();`); }
    finally { dialog.showOpenDialog=originalOpenDialog; }
    return (await run('return await window.batto.getState();')).config.appearance.chatIcons.local.customPath;
  };
  const firstLocalIcon=await uploadLocalIconFixture();
  assert.equal(fs.existsSync(firstLocalIcon),true);
  assert.deepEqual(nativeImage.createFromPath(firstLocalIcon).getSize(),{width:128,height:128});
  await run(`setView('dashboard');await window.batto.sendMessage({platform:'local',text:'QA LOCAL ICON'});`);
  await waitFor(()=>run(`const image=document.querySelector('.platform-icon.internal img');return !!image&&image.complete&&image.naturalWidth===128&&image.naturalHeight===128;`),'Local icon in Multi-Chat');
  const localIconResponse=await fetch('http://127.0.0.1:17777/assets/custom/local-chat-icon.png');
  assert.equal(localIconResponse.status,200);assert.match(localIconResponse.headers.get('content-type'),/^image\/png/);assert.ok((await localIconResponse.arrayBuffer()).byteLength>1000);
  const overlayIconWindow=new BrowserWindow({show:false,width:900,height:500});
  await overlayIconWindow.loadURL('http://127.0.0.1:17777/overlay/chat');
  await run(`await window.batto.sendMessage({platform:'local',text:'QA LOCAL OVERLAY ICON'});`);
  await waitFor(()=>overlayIconWindow.webContents.executeJavaScript(`(()=>{const image=document.querySelector('.platform.internal img');return !!image&&image.complete&&image.naturalWidth===128&&image.naturalHeight===128})()`),'Local icon in OBS overlay');
  fs.writeFileSync(path.join(dir,'05-Lokaler-Chat-Icon-Overlay.png'),(await overlayIconWindow.webContents.capturePage()).toPNG());
  overlayIconWindow.close();
  await run(`setView('settings');window.confirm=()=>true;await document.querySelector('#stLocalIconReset').onclick();`);
  await waitFor(()=>run(`return S.config.appearance.chatIcons.local.mode==='default';`),'Reset local chat icon');
  assert.equal(fs.existsSync(firstLocalIcon),false);assert.equal((await fetch('http://127.0.0.1:17777/assets/custom/local-chat-icon.png')).status,404);
  const customLocalIcon=await uploadLocalIconFixture();
  assert.equal(fs.existsSync(customLocalIcon),true);assert.deepEqual(nativeImage.createFromPath(customLocalIcon).getSize(),{width:128,height:128});
  await run(`document.querySelector('#localChatIconSettings').scrollIntoView({block:'start'});`);await capture('05-Lokaler-Chat-Icon-Einstellung');
  checks.push('Local chat/overlay icon: native upload, automatic center crop to 128x128 PNG, preview, Multi-Chat, HTTP overlay, reset cleanup and re-upload');
  await waitFor(()=>run(`return [...document.querySelectorAll('#familyBranding img')].every(i=>i.complete&&i.naturalWidth>0);`),'Sarah and Michelle decoded');
  await run(`document.querySelector('#familyBranding').scrollIntoView({block:'start'});`);await capture('04-Einstellungen-Logos');
  await run(`document.querySelector('#settingsAudio').scrollIntoView({block:'center'});`);await capture('05-TTS-Ausgabe');
  checks.push('Settings: both original logos render; speaker selection and volume share persisted TTS configuration');
  await run(`setView('platforms');`);
  await waitFor(()=>run(`return !!document.querySelector('#pfTikChatUrl');`),'TikFinity Chat URL field');
  assert.equal(await run(`return S.config.platforms.tikfinity.webWidgets.length;`),0);
  await run(`document.querySelector('#pfTikChatUrl').value='http://tikfinity.zerody.one/widget/chat?cid=676051';await document.querySelector('#pfTikChatSave').onclick();`);
  await waitFor(()=>run(`return S.config.platforms.tikfinity.webWidgets.some(w=>w.url==='https://tikfinity.zerody.one/widget/chat?cid=676051');`),'TikFinity Chat URL saved');
  await run(`document.querySelector('#pfTikUrl').value='https://tikfinity.zerody.one/widget/follow?cid=qa-installed';await document.querySelector('#pfSave').onclick();`);
  await waitFor(()=>run(`return S.config.platforms.tikfinity.webWidgets.some(w=>w.url==='https://tikfinity.zerody.one/widget/follow?cid=qa-installed');`),'HTTPS URL imported from WebSocket field');
  assert.match(await run(`return S.config.platforms.tikfinity.url;`),/^wss?:\/\//);
  const qaWidget=await run(`return S.config.platforms.tikfinity.webWidgets.find(w=>w.url==='https://tikfinity.zerody.one/widget/follow?cid=qa-installed');`);
  const qaRedirect=await fetch('http://127.0.0.1:17777/overlay/tikfinity/'+encodeURIComponent(qaWidget.id),{redirect:'manual'});
  assert.equal(qaRedirect.status,302);assert.equal(qaRedirect.headers.get('location'),qaWidget.url);
  checks.push('TikFinity HTTPS URL survives wrong-field paste, persists separately and has a stable OBS route');
  // Exercise the same normalizer and action engine on every platform with local-only outputs.
  await run(`await window.batto.saveConfig({commands:[...S.config.commands,{id:'qa-all',enabled:true,trigger:'!qa-all',platform:'all',cooldownSeconds:0,actions:[{type:'chat',platform:'local',text:'QA PLATFORM {platform}'}]}]});`);
  for(const platform of ['twitch','tiktok','cng','youtube']){
    globalThis.__battoEventCore.ingestChat({platform,id:'qa-'+platform,username:'Test_User',text:'!qa-all'},'qa-source');
    await waitFor(()=>run(`return (await window.batto.getState()).messages.some(m=>m.message==='QA PLATFORM ${platform}');`),'Command chain '+platform);
  }
  checks.push('Actual event core -> all-platform command -> local response for Twitch, TikTok, CNG, YouTube');
  await run(`setView('dashboard');await window.batto.detachChat();`);
  await waitFor(()=>run(`return ['tiktok','twitch','youtube','cng'].every(p=>!!document.querySelector('.platform-icon.'+p+' img'));`),'Platform logos in Multi-Chat');
  checks.push('Original source logos render on TikTok, Twitch, YouTube and CNG chat rows');
  const detached=await waitFor(()=>BrowserWindow.getAllWindows().find(w=>w!==win),'Detached window');
  const other=code=>detached.webContents.executeJavaScript(`(async()=>{${code}})()`,true);
  await waitFor(()=>other(`return document.body.classList.contains('detached')&&typeof S!=='undefined'&&!!S.config;`),'Detached renderer');
  assert.match(await other(`return getComputedStyle(document.querySelector('.chat-card')).backgroundImage;`),/chat-background-/);
  assert.match(await other(`return getComputedStyle(document.querySelector('.chat-card')).backgroundSize;`),/cover/);
  assert.equal(await other('return S.config.tts.volume;'),.37);
  await run(`await window.batto.sendMessage({platform:'local',text:'QA SHARED WINDOW'});`);
  await waitFor(()=>other(`return document.querySelector('#chatList').textContent.includes('QA SHARED WINDOW');`),'Shared chat history');
  fs.writeFileSync(path.join(dir,'06-Abgetrennter-Chat.png'),(await detached.webContents.capturePage()).toPNG());
  await capture('02-Multi-Chat');
  checks.push('Detached custom chat background, shared live history and settings; no second scheduler');
  detached.close();
  assert.equal((await fetch('http://127.0.0.1:17777/health')).status,200);
  assert.equal((await fetch('http://127.0.0.1:17777/state',{headers:{Origin:'https://untrusted.example'}})).status,403);
  checks.push('Overlay HTTP works; cross-origin access is denied');
  assert.deepEqual(await run('return window.__qaErrors;'),[]);
  const saved=JSON.parse(fs.readFileSync(path.join(profile,'Batto-OBS-Tool/settings.json'),'utf8'));
  assert.equal(saved.schemaVersion,5);assert.equal(saved.autoBroadcast.items.length,1);assert.equal(saved.autoBroadcast.items[0].name,'QA Broadcast B');assert.equal(saved.tts.volume,.37);
  assert.equal(saved.appearance.chatBackground.mode,'custom');assert.equal(saved.appearance.chatBackground.customName,'crazy-batto-chat-default.jpg');assert.equal(saved.appearance.chatBackground.fit,'cover');assert.equal(saved.appearance.chatBackground.darkness,.63);assert.equal(fs.existsSync(saved.appearance.chatBackground.customPath),true);
  assert.equal(saved.appearance.chatIcons.local.mode,'custom');assert.equal(saved.appearance.chatIcons.local.customName,'crazy-batto-chat-default.jpg');assert.equal(fs.existsSync(saved.appearance.chatIcons.local.customPath),true);assert.deepEqual(nativeImage.createFromPath(saved.appearance.chatIcons.local.customPath).getSize(),{width:128,height:128});
  const tikfinityChatUrl='https://tikfinity.zerody.one/widget/chat?cid=676051';assert.equal(saved.platforms.tikfinity.webWidgets.some(widget=>widget.url===tikfinityChatUrl),true);
  fs.writeFileSync(path.join(dir,'resume-expectations.json'),JSON.stringify({schemaVersion:5,broadcasts:1,broadcastName:'QA Broadcast B',volume:.37,tikfinityChatUrl,chatBackgroundName:'crazy-batto-chat-default.jpg',chatBackgroundPath:saved.appearance.chatBackground.customPath,localChatIconName:'crazy-batto-chat-default.jpg',localChatIconPath:saved.appearance.chatIcons.local.customPath}));
  await run(`setView('start');`);
  checks.push('No renderer errors; persisted schema-5 settings ready for independent restart test');
};
