const WebSocket=require('ws');
function pick(o,keys){for(const k of keys)if(o?.[k]!==undefined&&o?.[k]!==null)return o[k];}
class TikFinityAdapter{
  constructor({url='ws://127.0.0.1:21213/',reconnectSeconds=5,onMessage,onEvent,onStatus}){this.name='tikfinity';this.url=url;this.reconnectSeconds=reconnectSeconds;this.onMessage=onMessage;this.onEvent=onEvent;this.onStatus=onStatus;this.socket=null;this.timer=null;this.manualStop=false;this.capabilities={readChat:true,sendChat:false,moderation:false,events:true};this.status={name:this.name,connected:false,state:'idle',url};}
  getStatus(){return{...this.status,url:this.url,capabilities:{...this.capabilities}}} healthCheck(){const status=this.getStatus();return Promise.resolve({ok:Boolean(status.connected),status});} setStatus(p){this.status={...this.status,...p,url:this.url};this.onStatus?.(this.getStatus())} updateConfig(c={}){this.url=c.url||this.url;this.reconnectSeconds=Number(c.reconnectSeconds||5);this.setStatus({});}
  connect(){if(this.socket&&[WebSocket.OPEN,WebSocket.CONNECTING].includes(this.socket.readyState))return;this.manualStop=false;clearTimeout(this.timer);this.setStatus({state:'connecting',connected:false,error:null});try{this.socket=new WebSocket(this.url)}catch(e){this.setStatus({state:'error',error:e.message});return this.reconnect()}
    this.socket.on('open',()=>this.setStatus({state:'connected',connected:true,error:null}));this.socket.on('message',d=>this.handle(d));this.socket.on('error',e=>this.setStatus({state:'error',connected:false,error:e.message}));this.socket.on('close',()=>{this.socket=null;this.setStatus({state:this.manualStop?'stopped':'disconnected',connected:false});if(!this.manualStop)this.reconnect()});}
  reconnect(){if(this.manualStop)return;clearTimeout(this.timer);this.timer=setTimeout(()=>this.connect(),Math.max(1,this.reconnectSeconds)*1000)} disconnect(){this.manualStop=true;clearTimeout(this.timer);try{this.socket?.close()}catch{}this.socket=null;this.setStatus({state:'stopped',connected:false,error:null})}
  handle(data){let p;try{p=JSON.parse(data.toString('utf8'))}catch{return}const event=String(p?.event||p?.type||'').toLowerCase();const d=p?.data??p;if(event==='chat'||event==='comment'){const user=pick(d,['uniqueId','nickname','username','user','name']);const msg=pick(d,['comment','message','text','msg']);if(msg)this.onMessage?.({platform:'tiktok',userId:pick(d,['userId','userIdString','id']),username:user||'TikTokUser',displayName:pick(d,['nickname','displayName'])||user,message:String(msg),timestamp:new Date().toISOString(),moderator:Boolean(pick(d,['isModerator','moderator'])),raw:p});return}
    if(event)this.onEvent?.({source:'tikfinity',platform:'tiktok',event,data:d,timestamp:new Date().toISOString()});}
}
module.exports={TikFinityAdapter};
