const { spawn } = require('child_process');
function expand(text,ctx={}){return String(text??'').replace(/\{(\w+)\}/g,(_,k)=>ctx[k]??'');}
class ActionEngine{
  constructor({getConfig,sendChat,onTts,onOverlay,onLog}){this.getConfig=getConfig;this.sendChat=sendChat;this.onTts=onTts;this.onOverlay=onOverlay;this.onLog=onLog;this.commandCooldowns=new Map();}
  async handleMessage(message){const cfg=this.getConfig();for(const cmd of cfg.commands||[]){if(cmd.enabled===false)continue;const trigger=String(cmd.trigger||'').trim();if(!trigger)continue;const raw=message.message.trim();const match=cmd.caseSensitive?raw.startsWith(trigger):raw.toLowerCase().startsWith(trigger.toLowerCase());if(!match)continue;const key=`${message.platform}:${message.username}:${cmd.id||trigger}`;const now=Date.now(),until=this.commandCooldowns.get(key)||0;if(now<until)continue;this.commandCooldowns.set(key,now+Math.max(0,Number(cmd.cooldownSeconds||0))*1000);await this.execute(cmd.actions||[],{...message,user:message.displayName||message.username,platform:message.platform,command:trigger});}}
  async handleEvent(evt){const cfg=this.getConfig();for(const rule of cfg.events||[]){if(rule.enabled===false)continue;if(rule.platform&&rule.platform!=='all'&&rule.platform!==evt.platform)continue;if(String(rule.event||'').toLowerCase()!==String(evt.event||'').toLowerCase())continue;await this.execute(rule.actions||[],{...evt.data,event:evt.event,platform:evt.platform||evt.source||'tiktok'});}}
  async execute(actions,ctx={}){for(const a of actions){try{if(a.type==='delay')await new Promise(r=>setTimeout(r,Math.max(0,Number(a.ms||a.seconds*1000||0))));else if(a.type==='chat')await this.sendChat?.(a.platform||ctx.platform,expand(a.text,ctx));else if(a.type==='tts')this.onTts?.({text:expand(a.text||ctx.message||'',ctx),voice:a.voice||'',rate:a.rate||1,pitch:a.pitch||1,volume:a.volume??1});else if(a.type==='overlay')this.onOverlay?.({type:a.eventType||'custom',data:{...ctx,text:expand(a.text||'',ctx)}});else if(a.type==='hotkey')await this.hotkey(a);}catch(e){this.onLog?.('ERROR','Automation',e.message,{action:a})}}}
  hotkey(a){if(process.platform!=='win32')throw new Error('Hotkeys werden in diesem Build nur unter Windows ausgeführt.');const keys=String(a.keys||'').trim();if(!keys)throw new Error('Hotkey fehlt.');const target=String(a.process||'').trim();if(!target)throw new Error('Zielprozess für Hotkey fehlt.');const safeTarget=target.replace(/'/g,"''"),safeKeys=keys.replace(/'/g,"''");const ps=`$p=Get-Process -Name '${safeTarget}' -ErrorAction SilentlyContinue | Select-Object -First 1; if(-not $p){exit 7}; $w=New-Object -ComObject WScript.Shell; if(-not $w.AppActivate($p.Id)){exit 8}; Start-Sleep -Milliseconds 100; $w.SendKeys('${safeKeys}')`;return new Promise((resolve,reject)=>{const c=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',ps],{windowsHide:true});c.on('exit',code=>code===0?resolve():reject(new Error(`Hotkey fehlgeschlagen (Code ${code})`)));c.on('error',reject)})}
}
module.exports={ActionEngine,expand};
